using FFTW

# TODO: Check bluestein propagation implementation.
# We should check that the intensity and amplitudes are correct.

"""
    propagate_bluestein(field::ScalarField, z::Float64,
                        output_grid::TransverseGrid) -> ScalarField

Scalar diffraction propagation using the Bluestein/chirp-z transform method.
Allows independent control of input and output grid size and spacing,
avoiding the wraparound artifacts of standard FFT-based propagators.

The algorithm computes:

```math
E_{out}(u, v) = \\frac{e^{ikz}}{i\\lambda z}
\\exp\\!\\left(\\frac{ik(u^2+v^2)}{2z}\\right)
\\Delta x \\Delta y \\,
\\mathcal{F}_{\\text{CZT}}\\left\\{E_{in}(x,y)
\\exp\\!\\left(\\frac{i\\pi(x^2+y^2)}{\\lambda z}\\right)\\right\\}
```

where ``\\mathcal{F}_{\\text{CZT}}`` is the chirp-z transform evaluated
on the output grid coordinates.

# Arguments
- `field`      : input `ScalarField` at the source plane
- `z`          : propagation distance [m]
- `output_grid`: `TransverseGrid` defining the observation plane sampling.
                 Can have different size and spacing from the input grid.

# Notes
This method is particularly suited for:
- Diverging beams (paraboloidal, spherical waves)
- Large propagation distances where the field spreads beyond the input grid
- Cases requiring different input/output resolutions

# References
Hu et al., *Light: Science and Applications* 9, 119 (2020).
DOI: 10.1038/s41377-020-00362-z
"""
function propagate_bluestein(
  field       :: ScalarField,
  z           :: Float64,
  output_grid :: TransverseGrid{<:Real},
) :: ScalarField
  @assert z >= 0 "Propagation distance must be nonnegative"

  λ  = field.λ
  k  = 2π / λ

  dx = field.grid.dx
  dy = field.grid.dy
  Nx = field.grid.Nx
  Ny = field.grid.Ny

  Lx = (Nx - 1) * dx
  Ly = (Ny - 1) * dy
  X = range(-Lx/2,Lx/2,Nx)'
  Y = range(-Ly/2,Ly/2,Ny)

  U = output_grid.x'
  V = output_grid.y

  F0 = @. exp(1im*k*z) / (1im*λ*z) * exp(1im*k*(U^2 + V^2) / (2z))
  F  = @. exp(1im*k*(X^2 + Y^2) / (2z))

  fus = λ * z / dx
  fu  = U .+ fus / 2
  fvs = λ * z / dy
  fv  = V .+ fvs / 2

  E = dx * dy .* F0 .* _fft2_bluestein(field.U .* F, fu, fus, fv, fvs)

  return ScalarField(E, output_grid, λ)
end

function _fft2_bluestein(U, fx, fxs, fy, fys)
  fx1 = fx[1];   fx2 = fx[end];   Mx = length(fx)
  fy1 = fy[1];   fy2 = fy[end];   My = length(fy)
  return _fft_bluestein(
           _fft_bluestein(U, fx1, fx2, fxs, Mx; axis=1),
           fy1, fy2, fys, My; axis=2
         )
end

function _fft_bluestein(x, f1, f2, fs, M; axis=1)
  if axis == 1
    x = permutedims(x, [1, 2])
  else
    x = permutedims(x, [2, 1])
  end
  N = size(x, 1)

  A0 = 1; W0=1;

  f11 = f1 + (M*fs + f2 - f1) / (2 * M)
  f22 = f2 + (M*fs + f2 - f1) / (2 * M)
  df = f22-f11

  A = A0 * exp(1im * 2π * f11 / fs)
  W = W0 * exp(-1im * 2π * (f22 - f11) / (M*fs))

  M_shift = -N/2
  fv  = range(f11, step=df/M, length=M) # [f1, f1 + (1/M)df, ..., f1 + ((M-1)/M) * df]
  P_shift = @. exp(-1im * 2π * (M_shift) * fv / fs)
  X = mapslices(u -> P_shift .* _czt(u, M, A, W), x; dims=1)

  if axis == 1
    X = permutedims(X, [1, 2])
  else
    X = permutedims(X, [2, 1])
  end

  return X
end

"""
Compute the chirp z transform (czt) of x.
"""
function _czt(x, M, A, W)
  N = size(x, 1)
  X = zeros(ComplexF64, N)
  r = zeros(ComplexF64, N)
  c = zeros(ComplexF64, M)

  for i in 1:N
    k    = i - 1
    X[i] = W^(k^2/2) * A^(-k) * x[i]
    r[i] = W^(-k^2/2)
  end

  for i in 1:M
    k    = i - 1
    c[i] = W^(-k^2/2)
  end

  X = _toeplitz_multiply(r, c, X)

  for i in 1:M
    k    = i - 1
    X[i] = W^(k^2/2) * X[i]
  end

  return X
end

"""
Compute the product y = Tx of a Toeplitz matrix T and a vector x, where T is specified by its first row 
r = (r[0], r[1], r[2], . . . , r[N −1]) and its first column
c = (c[0], c[1], c[2], . . . , c[M −1]), where r[0] = c[0].
"""
function _toeplitz_multiply(r, c, x)
  N = length(r)
  M = length(c)
  n = Int(2^ceil(log2(M + N - 1)))
  c_hat = zeros(ComplexF64, n)

  for i in 1:M
    c_hat[i] = c[i]
  end

  for i in 2:N
    c_hat[n - i + 2] = r[i]
  end

  x_hat = _zeropad(x, n)
  y_hat = _circulant_multiply(c_hat, x_hat)

  y = zeros(ComplexF64, M)
  for i in 1:M
    y[i] = y_hat[i]
  end

  return y
end

"""
    _circulant_multiply(c, x)

Runs in O(n log n) time.
Compute the product y = Gx of a circulant matrix G
and a vector x, where G is generated by its first column
c = (c[0], c[1], . . . , c[n−1]).
"""
function _circulant_multiply(c, x)
  C = fft(c)
  X = fft(x)
  Y = zeros(ComplexF64, length(c))
  for i in 1:length(c)
    Y[i] = C[i] * X[i]
  end
  return ifft(Y)
end

function _zeropad(x, n)
  m     = length(x)
  x_hat = zeros(ComplexF64, n)
  for i in 1:m
    x_hat[i] = x[i]
  end
  return x_hat
end
